stages:
  prepare:
    cmd: python -m src.features.prepare
    deps:
    - data/raw/train-00000-of-00002.parquet
    - data/raw/train-00001-of-00002.parquet
    - src/features/prepare.py
    params:
    - prepare.random_state
    - prepare.test_size
    - prepare.train_size
    - prepare.valid_size
    outs:
    - data/processed/X_train.csv
    - data/processed/X_valid.csv
    - data/processed/y_train.csv
    - data/processed/y_valid.csv
    - data/processed/X_test.csv
    - data/processed/y_test.csv
  train:
    cmd: python -m src.models.train
    deps:
    - data/processed/X_train.csv
    - data/processed/y_train.csv
    - src/models/train.py
    params:
    - train.combinations
    - train.hyperparameters
    - train.targets
    outs:
    - models/
    - parameters_list.json
    - parameters_run.json
  evaluate:
    cmd: python -m src.models.evaluate
    deps:
    - data/processed/X_valid.csv
    - data/processed/y_valid.csv
    - models/
    - src/models/evaluate.py
    metrics:
    - metrics/scores.json:
        cache: false
