prepare:
  train_size: 0.01
  test_size: 0.025
  valid_size: 0.7
  random_state: 2024
train:
  combinations: 1
  targets: ["cat","dog"]
  hyperparameters:
    algorithm: ["VisualTransformer"]
    model_name: ["google/vit-base-patch16-224"]
    batch_size: [8, 16, 32]                 
    learning_rate: [0.00001, 0.00005, 0.0001]    
    num_epochs: [3]                 
    weight_decay: [0.0, 0.01, 0.1] 
    momentum: [0.9, 0.95, 0.99]                                  
    optimizer: ["adam", "sdg"]